esphome:
  name: olimex-test
  friendly_name: olimex-test

esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12
