substitutions:
  name: etekcity_esw01
  friendly_name: ETekCity ESW01
  version: "0.0.3"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ETekCity ESW01 Smart Plug
  name_add_mac_suffix: true
  project:
    name: "thewave1408.etekcity-esw01"
    version: "${version}"
  # esp8266_restore_from_flash: true
  # Can cause reduced flash lifetime due to frequent writes, enable as needed

esp8266:
  board: esp01_1m
  early_pin_init: False

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}_AP
    password: !secret wifi_password

captive_portal:

dashboard_import:
  package_import_url: github://thewave1408/ESPHome/etekcity/esw01.yaml
  import_full_config: false

# web_server:
  # port: 80
  # https://esphome.io/components/web_server.html
  # Can cause high memory usage on ESP8266, enable as needed

logger:
  level: INFO
  # https://esphome.io/components/logger

api:
  #encryption:
  #  key: !secret api_key
  # https://esphome.io/components/api

ota:
  platform: esphome
  id: ota_esphome

time:
  - platform: homeassistant

# Wi-Fi Link Status LED (Blue)
status_led:
  pin:
    number: GPIO5

# Outlet State LED (Yellow)
output:
  - platform: gpio
    id: led1
    pin: GPIO16

# Outlet Relay Button
switch:
  - platform: gpio
    name: "${friendly_name}"
    id: switch1
    pin: GPIO4
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      - output.turn_on: led1
    on_turn_off:
      - output.turn_off: led1
  - platform: restart
    name: "Restart"

# Outlet Relay Toggle When Button Pushed
binary_sensor:
  - platform: status
    name: "Status"
  - platform: gpio
    id: button1
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: switch1

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
    # disabled_by_default: true
    # entity_category: diagnostic
  - platform: uptime
    name: "Uptime seconds"
    id: uptime_s
    update_interval: 60s
    # disabled_by_default: true
  - platform: pulse_counter
    pin: GPIO12
    id: "gpio12"
    name: "GPIO12 counter"
    # internal: true
    entity_category: diagnostic
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 13us
    update_interval: 10s
    on_value:
      - sensor.template.publish:
          id: voltage
          state: !lambda 'return id(gpio12).state * 0.00623;'
      - sensor.template.publish:
          id: amps
          state: !lambda 'return id(watts).state / id(voltage).state;'
  - platform: pulse_counter
    pin: GPIO13
    id: "gpio13"
    name: "GPIO13 counter"
    # internal: true
    entity_category: diagnostic
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 13us
    update_interval: 10s
    on_value:
      - sensor.template.publish:
          id: watts
          state: !lambda  |-
            if (id(switch1).state) {
              return id(gpio13).state * 0.07708;
            } else {
              return 0;
            }
      - sensor.template.publish:
          id: amps
          state: !lambda 'return id(watts).state / id(voltage).state;'
  - platform: template
    id: voltage
    name: "Voltage"
    unit_of_measurement: "V"
  - platform: template
    id: watts
    name: "Watts"
    unit_of_measurement: "W"
  - platform: template
    id: amps
    unit_of_measurement: "A"
    name: "Amps"
    accuracy_decimals: 3

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    # ssid:
    #   name: "SSID"
  - platform: template
    name: "Uptime"
    lambda: |-
      uint32_t dur = id(uptime_s).state;
      int dys = 0;
      int hrs = 0;
      int mnts = 0;
      if (dur > 86399) {
        dys = trunc(dur / 86400);
        dur = dur - (dys * 86400);
      }
      if (dur > 3599) {
        hrs = trunc(dur / 3600);
        dur = dur - (hrs * 3600);
      }
      if (dur > 59) {
        mnts = trunc(dur / 60);
        dur = dur - (mnts * 60);
      }
      char buffer[17];
      sprintf(buffer, "%ud %02uh %02um %02us", dys, hrs, mnts, dur);
      return {buffer};
    icon: mdi:clock-start
    update_interval: 60s
    # disabled_by_default: true
    entity_category: diagnostic
